version: '3.4'

services:
  codebetterserver:
    image: codebetterserver
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
